title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          contact:
            type: object
            fields:
              email:
                type: email
              text:
                type: text
          instagram:
            type: object
            fields:
              link: 
                type: url
              text:
                type: text
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

